version: '3'

services:
  website:
    image: node:lts
    volumes:
      - ~/.ssh:/root/.ssh
      - nodemodules:/usr/src/aom/node_modules
      - .:/usr/src/aom
    working_dir: /usr/src/aom
    command: yarn start
    env_file:
      - .env
    ports:
      - 3001:3000

volumes:
  nodemodules:
    external: true
